### ISSUE TITLE
Creating new variable results in "Cannot read properties of undefined (reading 'value')" error

### ISSUE THREAD

**Issue by syphernl** [grafana/grafana-zabbix#1719]
**Describe the bug**
I'm trying to add a Variable to my Grafana dashboard using the wizard. 
I select `type = Query`, give it a name (`cluster`) and as soon as I switch Data source to `Zabbix` I get the error (see below).

If the name field is kept default (`query0`) and only a switch to the `Zabbix` datasource is being done it is working fine.

**Expected behavior**
No error

**Logs**
```txt
An unexpected error happened
Details
TypeError: Cannot read properties of undefined (reading 'value')

    at Vr (https://grafana.example.com/public/plugins/alexanderzobnin-zabbix-app/datasource/module.js:85:4275)
    at div
    at div
    at div
    at https://grafana.example.com/public/build/226.e8901bdbabf874bc7825.js:61:134931
    at Jp (https://grafana.example.com/public/build/226.e8901bdbabf874bc7825.js:4895:26727)
    at An (https://grafana.example.com/public/build/1486.9f5c58b5413b0650af69.js:172:120612)
    at form
    at Ee (https://grafana.example.com/public/build/226.e8901bdbabf874bc7825.js:1140:4597)
    at An (https://grafana.example.com/public/build/1486.9f5c58b5413b0650af69.js:172:120612)
    at div
    at div
    at div
    at div
    at Z (https://grafana.example.com/public/build/1486.9f5c58b5413b0650af69.js:137:79781)
    at r (https://grafana.example.com/public/build/226.e8901bdbabf874bc7825.js:61:29995)
    at div
    at A (https://grafana.example.com/public/build/226.e8901bdbabf874bc7825.js:457:4386)
    at Ze (https://grafana.example.com/public/build/226.e8901bdbabf874bc7825.js:1175:734)
    at An (https://grafana.example.com/public/build/1486.9f5c58b5413b0650af69.js:172:120612)
    at Ss (https://grafana.example.com/public/build/226.e8901bdbabf874bc7825.js:1196:9789)
    at it (https://grafana.example.com/public/build/DashboardPage.47d249f8c940b079c4b5.js:475:473)
    at DashboardPage
    at An (https://grafana.example.com/public/build/1486.9f5c58b5413b0650af69.js:172:120612)
    at Suspense
    at o (https://grafana.example.com/public/build/226.e8901bdbabf874bc7825.js:61:118536)
    at Sf (https://grafana.example.com/public/build/226.e8901bdbabf874bc7825.js:4857:330)
    at Oe (https://grafana.example.com/public/build/1486.9f5c58b5413b0650af69.js:203:23560)
    at Ki (https://grafana.example.com/public/build/1486.9f5c58b5413b0650af69.js:194:4727)
    at yt (https://grafana.example.com/public/build/1486.9f5c58b5413b0650af69.js:194:10218)
    at bu (https://grafana.example.com/public/build/1486.9f5c58b5413b0650af69.js:203:11747)
    at Oe (https://grafana.example.com/public/build/1486.9f5c58b5413b0650af69.js:203:25756)
    at div
    at div
    at main
    at div
    at Mi (https://grafana.example.com/public/build/226.e8901bdbabf874bc7825.js:4854:2396)
    at Ki (https://grafana.example.com/public/build/1486.9f5c58b5413b0650af69.js:194:4727)
    at yt (https://grafana.example.com/public/build/1486.9f5c58b5413b0650af69.js:194:10218)
    at Xe (https://grafana.example.com/public/build/1486.9f5c58b5413b0650af69.js:194:9607)
    at Zu (https://grafana.example.com/public/build/1486.9f5c58b5413b0650af69.js:203:12046)
    at Oe (https://grafana.example.com/public/build/1486.9f5c58b5413b0650af69.js:203:19731)
    at div
    at i (https://grafana.example.com/public/build/226.e8901bdbabf874bc7825.js:81:13223)
    at p (https://grafana.example.com/public/build/1486.9f5c58b5413b0650af69.js:37:13807)
    at h (https://grafana.example.com/public/build/1486.9f5c58b5413b0650af69.js:615:177459)
    at l (https://grafana.example.com/public/build/226.e8901bdbabf874bc7825.js:781:19710)
    at o (https://grafana.example.com/public/build/226.e8901bdbabf874bc7825.js:61:118536)
    at g (https://grafana.example.com/public/build/226.e8901bdbabf874bc7825.js:61:119045)
    at E (https://grafana.example.com/public/build/1486.9f5c58b5413b0650af69.js:172:118307)
    at Rf (https://grafana.example.com/public/build/226.e8901bdbabf874bc7825.js:4868:122)
```

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 10.1.5   | 6.4.7  | 4.4.3                 |

**Comment by zoltanbedi** [comment]
Hi @syphernl,
Thanks for creating this issue. I wasn't able to reproduce this issue. I tried with 10.1.5 and with the current main as well. Can you help me with a clear reproduction steps?

**Comment by syphernl** [comment]
The steps that cause this error most (not all) of the times:

* Ensure there are two data sources (e.g. Azure + Zabbix)
* Create a new dashboard
* Go to Dashboard Settings and then to Variables
* Click Add Variable
* Change data source to `Zabbix`

Sometimes it just works and when it works it sometimes also breaks whenever you swap the datasource again (e.g. Zabbix > Azure > Zabbix)
It seems to also trigger the same problem without even changing the name.
