### ISSUE TITLE
Can't execute scripts 

### ISSUE THREAD

**Issue by andrevader** [grafana/grafana-zabbix#1749]
**Describe the bug**
When I try to execute any scripts Zabbix, I received this error:

**request failed, status: 500 Internal Server Error**

When I see the log (apache2/error.log)

PHP Fatal error:  Uncaught TypeError: Argument 2 passed to CZabbixServer::executeScript() must be of the type string, null given, called in /usr/share/zabbix/include/classes/api/services/CScript.php on line 941 and defined in /usr/share/zabbix/include/classes/server/CZabbixServer.php:153\nStack trace:\n#0 /usr/share/zabbix/include/classes/api/services/CScript.php(941): CZabbixServer->executeScript()\n#1 /usr/share/zabbix/include/classes/api/clients/CLocalApiClient.php(121): CScript->execute()\n#2 /usr/share/zabbix/include/classes/core/CJsonRpc.php(75): CLocalApiClient->callMethod()\n#3 /usr/share/zabbix/api_jsonrpc.php(63): CJsonRpc->execute()\n#4 {main}\n  thrown in /usr/share/zabbix/include/classes/server/CZabbixServer.php on line 153

**Expected behavior**

**Screenshots**
![image](https://github.com/grafana/grafana-zabbix/assets/44476841/ebe205e5-1a86-4a35-bf7c-91800048c5ac)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 10.1.5   | 6.0.16  | 4.4.3                |

**Comment by reacher666** [comment]
Hi,
I had the same issue, but when calling Zabbix API with curl. I had Zabbix version 6.4.1 and after upgrading to 6.4.8 the problem was fixed.
So maybe try upgrading Zabbix server?
